const csgoCollections = [
  "Any",
  "The Alpha Collection",
  "The Assault Collection",
  "The Aztec Collection",
  "The Baggage Collection",
  "The Bank Collection",
  "The Blacksite Collection",
  "The Cache Collection",
  "The Canals Collection",
  "The Chop Shop Collection",
  "The Cobblestone Collection",
  "The Control Collection",
  "The Dust Collection",
  "The Dust 2 Collection",
  "The eSports 2013 Collection",
  "The eSports 2013 Winter Collection",
  "The eSports 2014 Summer Collection",
  "The Gods and Monsters Collection",
  "The Havoc Collection",
  "The Inferno Collection",
  "The Italy Collection",
  "The Lake Collection",
  "The Militia Collection",
  "The Mirage Collection",
  "The Norse Collection",
  "The Nuke Collection",
  "The Office Collection",
  "The Overpass Collection",
  "The Rising Sun Collection",
  "The Safehouse Collection",
  "The St. Marc Collection",
  "The Train Collection",
  "The Vertigo Collection",
  "The 2018 Inferno Collection",
  "The 2018 Nuke Collection",
  "The 2021 Dust 2 Collection",
  "The 2021 Mirage Collection",
  "The 2021 Train Collection",
  "The 2021 Vertigo Collection",
  "The Ancient Collection",
  "The Anubis Collection",
  "The Gallery Collection",
  "The Kilowatt Collection",
  "The Revolution Collection",
  "The Recoil Collection",
  "The Dreams & Nightmares Collection",
  "The Operation Riptide Collection",
  "The Snakebite Collection",
  "The Broken Fang Collection",
  "The Shattered Web Collection",
  "The Prisma Collection",
  "The Prisma 2 Collection",
  "The Spectrum Collection",
  "The Spectrum 2 Collection",
  "The Horizon Collection",
  "The Clutch Collection",
  "The Danger Zone Collection",
  "The CS20 Collection",
  "The Fracture Collection",
  "The X-Ray Collection",
  "The Wildfire Collection",
  "The Vanguard Collection",
  "The Phoenix Collection",
  "The Huntsman Collection",
  "The Breakout Collection",
  "The Bravo Collection",
  "The Arms Deal Collection",
  "The Arms Deal 2 Collection",
  "The Arms Deal 3 Collection",
  "The Graphic Design Collection",
  "The Sport & Field Collection",
  "The Overpass 2024 Collection",
  "Limited Edition Item",
];

export default csgoCollections;
